services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: API_sintrom
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    env_file:
      - .env